[package]
name = "iaia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.22.1"
glm = "0.2.3"
image = "0.24.3"
perlin2d = "0.2.6"
rand = "0.8.5"
